spring:
  main:
    allow-circular-references: true
  application:
    name: usuarios
  datasource:
    url: ${MYSQL_DATABASE_URL}
    username: ${MYSQL_DATABASE_USER}
    password: ${MYSQL_DATABASE_PWD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
springdoc:
  swagger-ui:
    path: /misproductos.html
    operationsSorter: method
